[package]
name = "normalisation-efficiency"
version = "0.1.0"
authors = ["OBenjaminT <oliver.wildwolf@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
